"""initial

Revision ID: 63436f3b2bd8
Revises: 
Create Date: 2026-04-19 19:23:00.566218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63436f3b2bd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_cost_per_1k', sa.Float(), nullable=False),
    sa.Column('completion_cost_per_1k', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('source_app', sa.String(length=128), nullable=True),
    sa.Column('endpoint', sa.String(length=64), nullable=True),
    sa.Column('integration_type', sa.String(length=32), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('time_to_first_token_ms', sa.Integer(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_per_second', sa.Float(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('completion_text', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_requests_model_name'), ['model_name'], unique=False)

    op.create_table('onprem_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=64), nullable=False),
    sa.Column('hardware_cost_usd', sa.Float(), nullable=False),
    sa.Column('amortization_months', sa.Integer(), nullable=True),
    sa.Column('power_draw_watts', sa.Float(), nullable=False),
    sa.Column('electricity_cost_kwh', sa.Float(), nullable=False),
    sa.Column('utilization_hours_day', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_name')
    )
    op.create_table('llm_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('judge_model', sa.String(length=128), nullable=True),
    sa.Column('coherence_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('judge_reasoning', sa.Text(), nullable=True),
    sa.Column('raw_judge_response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['llm_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['llm_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_feedback')
    op.drop_table('llm_evaluations')
    op.drop_table('onprem_config')
    with op.batch_alter_table('llm_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_requests_model_name'))
        batch_op.drop_index(batch_op.f('ix_llm_requests_created_at'))

    op.drop_table('llm_requests')
    op.drop_table('cloud_pricing')
    # ### end Alembic commands ###
